---
- name: Create Auto Scaling Group
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yaml
  tasks:
    - ec2_asg:
        name: team2_asg
        launch_config_name: team2-lc
        vpc_zone_identifier:
          - "{{subnet1}}"
          - "{{subnet2}}"
          - "{{subnet3}}"
        health_check_period: "{{health_check_period}}"
        health_check_type: "{{health_check_type}}"
        replace_all_instances: yes
        min_size: "{{min_size}}"
        max_size: "{{max_size}}"
        desired_capacity: "{{desired_capacity}}"
        region: "{{region}}"
        state: "{{state}}"
        # tags: "{{tags}}"
