---
- name: Auto Scaling Group
  hosts: localhost



  tasks: 
- name: Create launch configuration
  import_playbook: ec2_lc.yaml

- name: Create target group
  import_playbook: elb_target_group.yaml

- name: Create Application Load Balancer
  import_playbook: elb_application_lb.yaml

- name: Create Auto Scaling Group
  import_playbook: ec2_asg.yaml