---
- name: Launch Configuration
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars_file.yaml
  ignore_errors: true

  tasks:
  - name: create launch config
    ec2_lc:
      name: launch_asg
      image_id: ami-01d5e2046079dd35c
      key_name: ansible
      security_groups: launch-wizard-1
      instance_type: t2.micro
      region: eu-west-2
      volumes:
      - device_name: /dev/xvda
        volume_size: 100
        volume_type: io1
        iops: 3000
        delete_on_termination: true
        encrypted: no
    register: lc