---
- name: Auto Scaling Group
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars_file.yaml
  ignore_errors: no
  tasks:
  
  - ec2_asg:
      name: myasg
      launch_config_name: launch_asg
      health_check_period: 60
      health_check_type: ELB
      vpc_zone_identifier:
        - "{{subnet_1_AZ}}"
        - "{{subnet_2_AZ}}"
        - "{{subnet_3_AZ}}"
      replace_all_instances: yes
      min_size: "{{ min_size_instances }}"
      max_size: "{{ max_size_instances }}"
      desired_capacity: "{{ desired_capacity_instances }}"
      region: "{{ region }}"
      state: present