---
- name: Application Load Balancer
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars_file.yaml
  ignore_errors: no
  tasks:
  
  - elb_application_lb:
      name: myelb
      security_groups: Project2
      region: "{{ region }}"
      subnets:
        - "{{subnet_1_AZ}}"
        - "{{subnet_2_AZ}}"
        - "{{subnet_3_AZ}}"
      listeners:
      - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
        Port: 80 
        DefaultActions:
          - Type: forward # Required.
            TargetGroupName: mytargetgroup
      state: present