---
- name: Target Group
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars_file.yaml
  ignore_errors: no
  tasks:         
  - elb_target_group:
      name: mytargetgroup
      target_type: instance
      region: "{{ region }}"
      protocol: http
      port: 80
      vpc_id: "{{ vpc_id }}"
      health_check_path: /
      successful_response_codes: "200,250-260"
      state: present